<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
    <RootNamespace>SampleGame.Rest</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../SampleGame.Application/SampleGame.Application.csproj" />
    <PackageReference Include="BotFramework.Rest" Version="1.0.0" />
  </ItemGroup>
</Project>
