<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ChatAdministration.Application</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChatAdministration.Domain\ChatAdministration.Domain.csproj" />
  </ItemGroup>
</Project>
