// <auto-generated />
// Generated by namespace layout script; keeps references stable after folder-based namespaces.
global using BotFramework.Sdk.Admin;
global using BotFramework.Sdk.Commands;
global using BotFramework.Sdk.Configuration;
global using BotFramework.Sdk.Domain;
global using BotFramework.Sdk.Events.Bus;
global using BotFramework.Sdk.Events.Contracts;
global using BotFramework.Sdk.Events.Meta;
global using BotFramework.Sdk.Events.Store;
global using BotFramework.Sdk.Events.Telegram;
global using BotFramework.Sdk.Health;
global using BotFramework.Sdk.Metrics;
global using BotFramework.Sdk.MiniGames;
global using BotFramework.Sdk.Modules;
global using BotFramework.Sdk.Modules.Migrations;
global using BotFramework.Sdk.Projections;
global using BotFramework.Sdk.Snapshots;
